services:
  nodejs_authentication_api_test:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: nodejs_authentication_api_test
    ports:
      - 27017:27017
    volumes:
      - nodejs_authentication_api_test_mongo_data:/data/db

volumes:
  nodejs_authentication_api_test_mongo_data:
